### ISSUE TITLE
when I rosrun kinect2_bridge kinect2_bridge , occurs Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by 94zhaofang** [code-iai/iai_kinect2#489]
Two issues:
i. "rosrun kinect2_bridge kinect2_bridge", Segmentation fault (core dumped)
ii. "roslaunch kinect2_bridge kinect2_bridge.launch", [FATAL] [1527649735.162269400]: Failed to load nodelet '/kinect2_bridge` of type `kinect2_bridge/kinect2_bridge_nodelet` to manager `kinect2'
iii."gdb kinect2_bridge" results are the last.

fang@fang-ubuntu:~$ rosrun kinect2_bridge kinect2_bridge
[ INFO] [Kinect2Bridge::initialize] parameter:
        base_name: kinect2
           sensor: default
        fps_limit: -1
       calib_path: /home/fang/catkin_ws/iai_kinect2_catkin_ws/src/iai_kinect2/kinect2_bridge/data/
          use_png: false
     jpeg_quality: 90
        png_level: 1
     depth_method: opencl
     depth_device: -1
       reg_method: opencl
       reg_device: -1
        max_depth: 12
        min_depth: 0.1
       queue_size: 2
 bilateral_filter: true
edge_aware_filter: true
       publish_tf: false
     base_name_tf: kinect2
   worker_threads: 4
Segmentation fault (core dumped)
==================================================================================================================================================================

fang@fang-ubuntu:~$ roslaunch kinect2_bridge kinect2_bridge.launch
... logging to /home/fang/.ros/log/c7e59464-63b6-11e8-8e01-705a0f426a43/roslaunch-fang-ubuntu-2606.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://fang-ubuntu:34707/

SUMMARY
========

PARAMETERS
 * /kinect2_bridge/base_name: kinect2
 * /kinect2_bridge/base_name_tf: kinect2
 * /kinect2_bridge/bilateral_filter: True
 * /kinect2_bridge/calib_path: /home/fang/catkin...
 * /kinect2_bridge/depth_device: -1
 * /kinect2_bridge/depth_method: default
 * /kinect2_bridge/edge_aware_filter: True
 * /kinect2_bridge/fps_limit: -1.0
 * /kinect2_bridge/jpeg_quality: 90
 * /kinect2_bridge/max_depth: 12.0
 * /kinect2_bridge/min_depth: 0.1
 * /kinect2_bridge/png_level: 1
 * /kinect2_bridge/publish_tf: False
 * /kinect2_bridge/queue_size: 5
 * /kinect2_bridge/reg_device: -1
 * /kinect2_bridge/reg_method: default
 * /kinect2_bridge/sensor: 
 * /kinect2_bridge/use_png: False
 * /kinect2_bridge/worker_threads: 4
 * /kinect2_points_xyzrgb_hd/queue_size: 5
 * /kinect2_points_xyzrgb_qhd/queue_size: 5
 * /kinect2_points_xyzrgb_sd/queue_size: 5
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /
    kinect2 (nodelet/nodelet)
    kinect2_bridge (nodelet/nodelet)
    kinect2_points_xyzrgb_hd (nodelet/nodelet)
    kinect2_points_xyzrgb_qhd (nodelet/nodelet)
    kinect2_points_xyzrgb_sd (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [2636]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to c7e59464-63b6-11e8-8e01-705a0f426a43
process[rosout-1]: started with pid [2649]
started core service [/rosout]
process[kinect2-2]: started with pid [2652]
process[kinect2_bridge-3]: started with pid [2653]
process[kinect2_points_xyzrgb_sd-4]: started with pid [2654]
process[kinect2_points_xyzrgb_qhd-5]: started with pid [2655]
process[kinect2_points_xyzrgb_hd-6]: started with pid [2656]
[ INFO] [1527649733.188623786]: Loading nodelet /kinect2_bridge of type kinect2_bridge/kinect2_bridge_nodelet to manager kinect2 with the following remappings:
[ INFO] [1527649733.192839128]: waitForService: Service [/kinect2/load_nodelet] has not been advertised, waiting...
[ INFO] [1527649733.279522688]: Initializing nodelet with 8 worker threads.
[ INFO] [1527649733.298373143]: waitForService: Service [/kinect2/load_nodelet] is now available.
[ INFO] [1527649734.244030497]: [Kinect2Bridge::initialize] parameter:
        base_name: kinect2
           sensor: default
        fps_limit: -1
       calib_path: /home/fang/catkin_ws/iai_kinect2_catkin_ws/src/iai_kinect2/kinect2_bridge/data/
          use_png: false
     jpeg_quality: 90
        png_level: 1
     depth_method: default
     depth_device: -1
       reg_method: default
       reg_device: -1
        max_depth: 12
        min_depth: 0.1
       queue_size: 5
 bilateral_filter: true
edge_aware_filter: true
       publish_tf: false
     base_name_tf: kinect2
   worker_threads: 4
[FATAL] [1527649735.162269400]: Failed to load nodelet '/kinect2_bridge` of type `kinect2_bridge/kinect2_bridge_nodelet` to manager `kinect2'
[kinect2-2] process has died [pid 2652, exit code -11, cmd /opt/ros/indigo/lib/nodelet/nodelet manager __name:=kinect2 __log:=/home/fang/.ros/log/c7e59464-63b6-11e8-8e01-705a0f426a43/kinect2-2.log].
log file: /home/fang/.ros/log/c7e59464-63b6-11e8-8e01-705a0f426a43/kinect2-2*.log
[kinect2_bridge-3] process has died [pid 2653, exit code 255, cmd /opt/ros/indigo/lib/nodelet/nodelet load kinect2_bridge/kinect2_bridge_nodelet kinect2 __name:=kinect2_bridge __log:=/home/fang/.ros/log/c7e59464-63b6-11e8-8e01-705a0f426a43/kinect2_bridge-3.log].
log file: /home/fang/.ros/log/c7e59464-63b6-11e8-8e01-705a0f426a43/kinect2_bridge-3*.log
[kinect2_bridge-3] restarting process
process[kinect2_bridge-3]: started with pid [2884]
[ INFO] [1527649735.489066003]: Loading nodelet /kinect2_bridge of type kinect2_bridge/kinect2_bridge_nodelet to manager kinect2 with the following remappings:
[ INFO] [1527649735.491047558]: waitForService: Service [/kinect2/load_nodelet] could not connect to host [fang-ubuntu:47353], waiting...
[kinect2_points_xyzrgb_sd-4] process has finished cleanly
log file: /home/fang/.ros/log/c7e59464-63b6-11e8-8e01-705a0f426a43/kinect2_points_xyzrgb_sd-4*.log
[kinect2_points_xyzrgb_qhd-5] process has finished cleanly
log file: /home/fang/.ros/log/c7e59464-63b6-11e8-8e01-705a0f426a43/kinect2_points_xyzrgb_qhd-5*.log
[kinect2_points_xyzrgb_hd-6] process has finished cleanly
log file: /home/fang/.ros/log/c7e59464-63b6-11e8-8e01-705a0f426a43/kinect2_points_xyzrgb_hd-6*.log
[kinect2_points_xyzrgb_sd-4] restarting process
process[kinect2_points_xyzrgb_sd-4]: started with pid [3373]
[kinect2_points_xyzrgb_qhd-5] restarting process
process[kinect2_points_xyzrgb_qhd-5]: started with pid [3374]
[kinect2_points_xyzrgb_hd-6] restarting process
process[kinect2_points_xyzrgb_hd-6]: started with pid [3375]
^C[kinect2_points_xyzrgb_hd-6] killing on exit
[kinect2_points_xyzrgb_qhd-5] killing on exit
[kinect2_points_xyzrgb_sd-4] killing on exit
[kinect2_bridge-3] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
==================================================================================================================================================================

fang@fang-ubuntu:~/catkin_ws/iai_kinect2_catkin_ws/devel/lib/kinect2_bridge$ gdb kinect2_bridge 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from kinect2_bridge...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/fang/catkin_ws/iai_kinect2_catkin_ws/devel/lib/kinect2_bridge/kinect2_bridge 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdfefc700 (LWP 32592)]
[New Thread 0x7fffdee0e700 (LWP 32593)]
[New Thread 0x7fffde60d700 (LWP 32594)]
[New Thread 0x7fffdde0c700 (LWP 32595)]
[ERROR] [registerPublisher] Failed to contact master at [localhost:11311].  Retrying...
[ INFO] Connected to master at [localhost:11311]
[New Thread 0x7fffdd60b700 (LWP 32700)]
[New Thread 0x7fffd7fff700 (LWP 32701)]
[ INFO] [Kinect2Bridge::initialize] parameter:
        base_name: kinect2
           sensor: default
        fps_limit: -1
       calib_path: /home/fang/catkin_ws/iai_kinect2_catkin_ws/src/iai_kinect2/kinect2_bridge/data/
          use_png: false
     jpeg_quality: 90
        png_level: 1
     depth_method: opencl
     depth_device: -1
       reg_method: opencl
       reg_device: -1
        max_depth: 12
        min_depth: 0.1
       queue_size: 2
 bilateral_filter: true
edge_aware_filter: true
       publish_tf: false
     base_name_tf: kinect2
   worker_threads: 4
[New Thread 0x7fffc3ba6700 (LWP 32744)]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffd45716f1 in llvm::cl::AddLiteralOption(llvm::cl::Option&, char const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.8.so.1
(gdb) bt
#0  0x00007fffd45716f1 in llvm::cl::AddLiteralOption(llvm::cl::Option&, char const*) () from /usr/lib/x86_64-linux-gnu/libLLVM-3.8.so.1
#1  0x00007fffbfce2f4c in ?? () from /usr/lib/x86_64-linux-gnu/libLLVM-3.6.so.1
#2  0x00007ffff7dea1da in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffd968, env=env@entry=0x6ca4c0) at dl-init.c:78
#3  0x00007ffff7dea2c3 in call_init (env=<optimized out>, argv=<optimized out>, argc=<optimized out>, l=<optimized out>) at dl-init.c:36
#4  _dl_init (main_map=main_map@entry=0x6db670, argc=1, argv=0x7fffffffd968, env=0x6ca4c0) at dl-init.c:126
#5  0x00007ffff7deed00 in dl_open_worker (a=a@entry=0x7fffffffb088) at dl-open.c:577
#6  0x00007ffff7dea094 in _dl_catch_error (objname=objname@entry=0x7fffffffb078, errstring=errstring@entry=0x7fffffffb080, 
    mallocedp=mallocedp@entry=0x7fffffffb070, operate=operate@entry=0x7ffff7deea30 <dl_open_worker>, args=args@entry=0x7fffffffb088) at dl-error.c:187
#7  0x00007ffff7dee44b in _dl_open (file=0x7fffc2f424d8 "/usr/lib/x86_64-linux-gnu/beignet//libgbe.so", mode=-2147483647, 
    caller_dlopen=<optimized out>, nsid=-2, argc=1, argv=0x7fffffffd968, env=0x6ca4c0) at dl-open.c:661
#8  0x00007fffeacca02b in dlopen_doit (a=a@entry=0x7fffffffb2a0) at dlopen.c:66
#9  0x00007ffff7dea094 in _dl_catch_error (objname=0x66cae0, errstring=0x66cae8, mallocedp=0x66cad8, operate=0x7fffeacc9fd0 <dlopen_doit>, 
    args=0x7fffffffb2a0) at dl-error.c:187
#10 0x00007fffeacca62d in _dlerror_run (operate=operate@entry=0x7fffeacc9fd0 <dlopen_doit>, args=args@entry=0x7fffffffb2a0) at dlerror.c:163
#11 0x00007fffeacca0c1 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#12 0x00007fffc2f26853 in GbeLoaderInitializer::LoadCompiler() () from /usr/lib/x86_64-linux-gnu/beignet//libcl.so
#13 0x00007fffc2f1add7 in ?? () from /usr/lib/x86_64-linux-gnu/beignet//libcl.so
#14 0x00007ffff7dea1da in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffd968, env=env@entry=0x6ca4c0) at dl-init.c:78
#15 0x00007ffff7dea2c3 in call_init (env=<optimized out>, argv=<optimized out>, argc=<optimized out>, l=<optimized out>) at dl-init.c:36
#16 _dl_init (main_map=main_map@entry=0x6da840, argc=1, argv=0x7fffffffd968, env=0x6ca4c0) at dl-init.c:126
#17 0x00007ffff7deed00 in dl_open_worker (a=a@entry=0x7fffffffb588) at dl-open.c:577
#18 0x00007ffff7dea094 in _dl_catch_error (objname=objname@entry=0x7fffffffb578, errstring=errstring@entry=0x7fffffffb580, 
    mallocedp=mallocedp@entry=0x7fffffffb570, operate=operate@entry=0x7ffff7deea30 <dl_open_worker>, args=args@entry=0x7fffffffb588) at dl-error.c:187
---Type <return> to continue, or q <return> to quit---
#19 0x00007ffff7dee44b in _dl_open (file=0x7af560 "/usr/lib/x86_64-linux-gnu/beignet//libcl.so", mode=-2147483647, caller_dlopen=<optimized out>, 
    nsid=-2, argc=1, argv=0x7fffffffd968, env=0x6ca4c0) at dl-open.c:661
#20 0x00007fffeacca02b in dlopen_doit (a=a@entry=0x7fffffffb7a0) at dlopen.c:66
#21 0x00007ffff7dea094 in _dl_catch_error (objname=0x66cae0, errstring=0x66cae8, mallocedp=0x66cad8, operate=0x7fffeacc9fd0 <dlopen_doit>, 
    args=0x7fffffffb7a0) at dl-error.c:187
#22 0x00007fffeacca62d in _dlerror_run (operate=operate@entry=0x7fffeacc9fd0 <dlopen_doit>, args=args@entry=0x7fffffffb7a0) at dlerror.c:163
#23 0x00007fffeacca0c1 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#24 0x00007fffedfd12fb in ?? () from /usr/lib/x86_64-linux-gnu/libOpenCL.so.1
#25 0x00007fffedfd1459 in ?? () from /usr/lib/x86_64-linux-gnu/libOpenCL.so.1
#26 0x00007fffedfd19c2 in ?? () from /usr/lib/x86_64-linux-gnu/libOpenCL.so.1
#27 0x00007fffedfd2233 in clGetPlatformIDs () from /usr/lib/x86_64-linux-gnu/libOpenCL.so.1
#28 0x00007ffff56d77f6 in cl::Platform::get (platforms=platforms@entry=0x7fffffffba00)
    at /home/fang/tools/libfreenect2/include/internal/CL/cl.hpp:2338
#29 0x00007ffff56d94e5 in libfreenect2::OpenCLDepthPacketProcessorImpl::initDevice (this=this@entry=0x6a1920, deviceId=deviceId@entry=-1)
    at /home/fang/tools/libfreenect2/src/opencl_depth_packet_processor.cpp:431
#30 0x00007ffff56d9e9c in libfreenect2::OpenCLDepthPacketProcessorImpl::OpenCLDepthPacketProcessorImpl (this=0x6a1920, deviceId=-1)
    at /home/fang/tools/libfreenect2/src/opencl_depth_packet_processor.cpp:245
#31 0x00007ffff56d3ff1 in libfreenect2::OpenCLDepthPacketProcessor::OpenCLDepthPacketProcessor (this=0x6a01e0, deviceId=-1)
    at /home/fang/tools/libfreenect2/src/opencl_depth_packet_processor.cpp:721
#32 0x00007ffff56b6336 in libfreenect2::OpenCLPacketPipeline::OpenCLPacketPipeline (this=0x65b040, deviceId=-1)
    at /home/fang/tools/libfreenect2/src/packet_pipeline.cpp:151
#33 0x00000000004138f8 in Kinect2Bridge::initPipeline(std::string const&, int) ()
#34 0x00000000004292f4 in Kinect2Bridge::initialize() ()
---Type <return> to continue, or q <return> to quit---q
Quit
(gdb) q
A debugging session is active.

	Inferior 1 [process 32578] will be killed.

Quit anyway? (y or n) y

===============================================================================
These troubles me few days, I even try every solutions only if can search on the internet, but they doesn't work. Please help me, thank you very much.

**Comment by ChristophBrasseur** [comment]
I am running into the same issues. Have you found a solution yet?
